# Generated by Django 3.1.2 on 2020-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16),
        ),
    ]
