# Generated by Django 3.1.2 on 2020-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0003_auto_20201008_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
